### ISSUE TITLE
PECL/QA

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/pcov#1]
Hi @remicollet ... it's me again ... are you up for it ? (please)

**Comment by remicollet** [comment]
Of course !!

**Comment by remicollet** [comment]
Perhaps you can create the usual develop/release branch now
(so I will create the package.xml only in the release branch)

**Comment by remicollet** [comment]
Do you want me to send to request for feedback on pecl ML ?

**Comment by krakjoe** [comment]
I'll do that, and if you could do the internals mail, that'd be great ...

**Comment by remicollet** [comment]
http://news.php.net/php.pecl.dev/15698

**Comment by krakjoe** [comment]
Morning Remi ... I think this is ready for pecl when you are ;)

**Comment by remicollet** [comment]
Do we go with 0.0.1 beta ? or do you prefer something higher ?
How close are we from a "stable" API ?

**Comment by remicollet** [comment]
Package created: https://pecl.php.net/package/pcov

**Comment by krakjoe** [comment]
Well ... I've run pcov on every big project out there, it appears stable, and the API is certainly stable ... I'm going to leave it to you, as my very talented RM :)

**Comment by remicollet** [comment]
So, probably fine to release "0.9.0" beta to show we are close to "1.0.0 stable"
(I don't think any project should start public release as "stable", we really need some feedback)

**Comment by krakjoe** [comment]
You're right, good call ...

**Comment by remicollet** [comment]
Usual test build, with test suite, done

* Fedora 26 to 29, RHEL 6, 7 and 8-Beta
* i386, x86_64, NTS, ZTS

Everything looks good.
So released and announced
