### ISSUE TITLE
PHP 8.4 support

### ISSUE THREAD

**Issue by AlexSkrypnyk** [krakjoe/pcov#114]
With PHP 8.4 out, PCOV is not currently working with it because of https://github.com/krakjoe/pcov/pull/111

What are the plans for the relase?

I'm happy to sponsor this work to get it out ASAP.

**Comment by AlexSkrypnyk** [comment]
@remicollet
With Joe being away, can you please advise on the plans around new releases

**Comment by hydrapolic** [comment]
With https://github.com/krakjoe/pcov/pull/111 being merged, seems like it's on the way https://github.com/krakjoe/pcov/commit/6e42371d9d424f49a7a3d832ee9a1cc5a063553a.

Thanks @remicollet

**Comment by remicollet** [comment]
1.0.12 released
