### ISSUE TITLE
I broke the windows build

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/pcov#3]
Hi @weltling ... can you update the config.w32 to match config.m4 and drop 7.0 from CI please ?

**Comment by krakjoe** [comment]
I've had a go at fixing it ... but it still fails on x64 for some reason, not sure why ... any clue s?

**Comment by weltling** [comment]
@krakjoe i'll come to it this WE, probably tomorrow.

Thansk.

**Comment by krakjoe** [comment]
Thanks very much, appreciated :)

**Comment by weltling** [comment]
Fixed [here](https://github.com/krakjoe/pcov/commit/6c92cf1477350d608124167db5d97d6d56242790). `struct stat` is always 32 bit on Windows, `zend_stat_t` is a dynamic type just like `zend_long` is. That's it :)

**Comment by krakjoe** [comment]
Ah, well spotted ... thanks for that :)
