### ISSUE TITLE
Problem with whitelist and directories

### ISSUE THREAD

**Issue by kubawerlos** [krakjoe/pcov#31]
I've created  [this](https://github.com/kubawerlos/pcov-bug) repo (2 dummy classes, 100% code coverage expected).

Simple structure:
```json
{
    "autoload-dev": {
        "psr-4": {
            "TheFoo\\": "./src",
            "TheFooDev\\": "./dev-code"
        }
    }
}
```

Whitelist:
```xml
    <filter>
        <whitelist>
            <directory>dev-code</directory>
            <directory>src</directory>
        </whitelist>
    </filter>
```

On `master` branch [this](https://travis-ci.com/kubawerlos/pcov-bug/builds/129602575) build reports for xdebug and phpdbg 100% coverage (which is correct) and for pcov 50% (one class instead of two).

When I [rename](https://github.com/kubawerlos/pcov-bug/pull/1/files) `src` to `not-src` then suddenly all is [good](https://travis-ci.com/kubawerlos/pcov-bug/builds/129603067) - all 3 jobs reports 100% coverage.

When I [rename](https://github.com/kubawerlos/pcov-bug/pull/2/files) `dev-code` to `src-code` then again, all is [good]https://travis-ci.com/kubawerlos/pcov-bug/builds/129603756) - all 3 jobs reports 100% coverage.

Can it be related to `pcov.directory`? But the 2nd rename shows that it is not directory, but directory prefix (as both `src` and `src-code` are considered).

**Comment by mtorromeo** [comment]
I've had this same issue and it is indeed related to `pcov.directory`.
The problem is described in the README under the NOTES section:

> When pcov.directory is left unset, PCOV will attempt to find src, lib or, app in the current working directory, in that order; If none are found the current directory will be used, which may waste resources storing coverage information for the test suite.

So if you do not set `pcov.directory` and one of src, lib or app is found, no other directory is considered.

**Comment by kubawerlos** [comment]
My conclusion after some checking is that `pcov.directory` is used as path prefix, not directory.
