### ISSUE TITLE
Relative paths in clover file

### ISSUE THREAD

**Issue by tomasfejfar** [krakjoe/pcov#36]
When running pcov in docker it outputs the docker absolute paths in clover file. But when I want to use them in PhpStorm to show coverage, it obviously does not work, because the absolute paths are not available. Would it be possible to resolve the absolute paths relative to the current working directory?

**Comment by tomasfejfar** [comment]
Oh, I replaced the paths to relative manually, but that did not help. I'll investigate further.

**Comment by krakjoe** [comment]
This sounds like an issue you want to report to the php-code-coverage repo, pcov is not responsible for this output.

**Comment by tomasfejfar** [comment]
You're right! Sorry!
