### ISSUE TITLE
PCOV doesn't work with paratest? 

### ISSUE THREAD

**Issue by hgpull** [krakjoe/pcov#38]
I can’t understand if my configuration error or if pcov cannot be started with paratest.
I execute the command:

` /usr/bin/php -d memory_limit=2G -d pcov.enabled=1 -d pcov.directory=/srv/http/api.zp.ru/scripts/Job /srv/http/api.zp.ru/vendor/bin/phpunit -c /srv/http/api.zp.ru/tests/functional/phpunit.xml --coverage-text /srv/http/api.zp.ru/tests/functional/scripts/Job/Users`

and get result 

> Code Coverage Report:         
>   2019-11-24 14:16:14         
>                               
>  Summary:                     
>   Classes:  2.51% (46/1831)   
>   Methods:  7.02% (727/10361) 
>   Lines:    7.45% (4754/63852)

so, when run :

`/usr/bin/php -d memory_limit=2G -d pcov.enabled=1 -d pcov.directory=/srv/http/api.zp.ru/scripts/Job /srv/http/api.zp.ru/vendor/bin/paratest -p 4 -c /srv/http/api.zp.ru/tests/functional/phpunit.xml --coverage-text /srv/http/api.zp.ru/tests/functional/scripts/Job/Users `

we get zero result =( 

> Code Coverage Report:       
>   2019-11-24 14:18:38       
>                             
>  Summary:                   
>   Classes:  0.00% (0/1831)  
>   Methods:  0.00% (0/10362) 
>   Lines:    0.00% (0/110095)

Am I missing something?

**Comment by rask** [comment]
I think paratest has a `--passthru` command argument that allows you to pass through the PHP INI config that sets up PCOV. Paratest spawns new PHP processes by itself so you need to instruct the INI configs differently.

**Comment by krakjoe** [comment]
This is outside the scope of issues (for this project, try paratest).
