### ISSUE TITLE
Empty results

### ISSUE THREAD

**Issue by ext-pewa** [krakjoe/pcov#42]
Tests run and report is generated as normal, however, the coverage report shows 0% all the way through.

If I run the same config using phpdbg or Xdebug, it takes a lot longer, but it yields correct results.

I suspect it may be related to processIsolation? Here is my config

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap                   = "tests/bootstrap.php"
         backupGlobals               = "false"
         backupStaticAttributes      = "false"
         colors                      = "true"
         convertErrorsToExceptions   = "true"
         convertNoticesToExceptions  = "true"
         convertWarningsToExceptions = "true"
         processIsolation            = "true"
         stopOnFailure               = "false">
    <php>
        <env name="APP_ENV" value="test"/>
    </php>
    
    <testsuites>
        <testsuite name="Unit Tests">
            <directory>tests/unit</directory>
        </testsuite>
    </testsuites>

    <logging>
        <log type="coverage-html" target=".output/report" />
    </logging>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
</phpunit>
```

**Comment by fezfez** [comment]
please send your `composer show`

**Comment by ext-pewa** [comment]
> please send your `composer show`

```doctrine/instantiator              1.3.0   A small, lightweight utility to instantiate objects in PHP without invoking their construc...
myclabs/deep-copy                  1.9.4   Create deep copies (clones) of your objects
phar-io/manifest                   1.0.3   Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    2.0.1   Library for handling version information and constraints
phpdocumentor/reflection-common    2.0.0   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.2   With this component, a library can provide support for annotations via DocBlocks or otherw...
phpdocumentor/type-resolver        1.0.1   A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                   1.10.0  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          7.0.10  Library that provides collection, processing, and rendering functionality for PHP code cov...
phpunit/php-file-iterator          2.0.2   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1   Simple template engine.
phpunit/php-timer                  2.1.2   Utility class for timing
phpunit/php-token-stream           3.1.1   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    8.5.0   The PHP Unit Testing framework.
sebastian/code-unit-reverse-lookup 1.0.1   Looks up which function or method a line of code belongs to
sebastian/comparator               3.0.2   Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.2   Diff implementation
sebastian/environment              4.2.3   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.2   Provides the functionality to export PHP variables for visualization
sebastian/global-state             3.0.0   Snapshotting of global state
sebastian/object-enumerator        3.0.3   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations      2.0.1   Provides a list of PHP built-in functions that operate on resources
sebastian/type                     1.1.3   Collection of value objects that represent the types of the PHP type system
sebastian/version                  2.0.1   Library that helps with managing the version number of Git-hosted PHP projects
symfony/polyfill-ctype             v1.13.1 Symfony polyfill for ctype functions
theseer/tokenizer                  1.1.3   A small library for converting tokenized PHP source code into XML and potentially other fo...
webmozart/assert                   1.6.0   Assertions to validate method input/output with nice error messages.```

**Comment by jeff1326** [comment]
I have the same problem, here my `composer show` if you want to do a correlation

> barryvdh/laravel-debugbar             v3.2.8                                    PHP Debugbar integration for Laravel
> beyondcode/laravel-dump-server        1.3.0                                     Symfony Var-Dump Server for Laravel
> dnoegel/php-xdg-base-dir              v0.1.1                                    implementation of xdg base directory specification for php
> doctrine/inflector                    1.3.1                                     Common String Manipulations with regard to casing and singular...
> doctrine/instantiator                 1.3.0                                     A small, lightweight utility to instantiate objects in PHP wit...
> doctrine/lexer                        1.2.0                                     PHP Doctrine Lexer parser library that can be used in Top-Down...
> dragonmantank/cron-expression         v2.3.0                                    CRON for PHP: Calculate the next or previous run date and dete...
> egulias/email-validator               2.1.14                                    A library for validating emails against several RFCs
> erusev/parsedown                      1.7.4                                     Parser for Markdown.
> fideloper/proxy                       4.2.2                                     Set trusted proxies for Laravel
> filp/whoops                           2.7.1                                     php error handling for cool kids
> fzaninotto/faker                      v1.9.1                                    Faker is a PHP library that generates fake data for you.
> guzzlehttp/guzzle                     6.5.2                                     Guzzle is a PHP HTTP client library
> guzzlehttp/promises                   v1.3.1                                    Guzzle promises library
> guzzlehttp/psr7                       1.6.1                                     PSR-7 message implementation that also provides common utility...
> hamcrest/hamcrest-php                 v2.0.0                                    This is the PHP port of Hamcrest Matchers
> jakub-onderka/php-console-color       v0.2                                     
> jakub-onderka/php-console-highlighter v0.4                                      Highlight PHP code in terminal
> kitetail/zttp                         v0.4.0                                    A developer-experience focused HTTP client, optimized for most...
> laravel/framework                     v5.8.36                                   The Laravel Framework.
> laravel/tinker                        v1.0.10                                   Powerful REPL for the Laravel framework.
> league/flysystem                      1.0.63                                    Filesystem abstraction: Many filesystems, one API.
> maximebf/debugbar                     v1.15.1                                   Debug bar in the browser for php application
> mockery/mockery                       1.3.1                                     Mockery is a simple yet flexible PHP mock object framework
> monolog/monolog                       1.25.3                                    Sends your logs to files, sockets, inboxes, databases and vari...
> myclabs/deep-copy                     1.9.4                                     Create deep copies (clones) of your objects
> nesbot/carbon                         2.28.0                                    An API extension for DateTime that supports 281 different lang...
> nikic/php-parser                      v4.3.0                                    A PHP parser written in PHP
> nunomaduro/collision                  v2.1.1                                    Cli error handling for console/command-line PHP applications.
> opis/closure                          3.5.1                                     A library that can be used to serialize closures (anonymous fu...
> paragonie/random_compat               v9.99.99                                  PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
> paragonie/sodium_compat               v1.12.2                                   Pure PHP implementation of libsodium; uses the PHP extension i...
> phar-io/manifest                      1.0.3                                     Component for reading phar.io manifest information from a PHP ...
> phar-io/version                       2.0.1                                     Library for handling version information and constraints
> phpdocumentor/reflection-common       2.0.0                                     Common reflection classes used by phpdocumentor to reflect the...
> phpdocumentor/reflection-docblock     4.3.4                                     With this component, a library can provide support for annotat...
> phpdocumentor/type-resolver           1.0.1                                     A PSR-5 based resolver of Class names, Types and Structural El...
> phpoption/phpoption                   1.7.2                                     Option Type for PHP
> phpspec/prophecy                      1.10.1                                    Highly opinionated mocking framework for PHP 5.3+
> phpunit/php-code-coverage             6.1.4                                     Library that provides collection, processing, and rendering fu...
> phpunit/php-file-iterator             2.0.2                                     FilterIterator implementation that filters files based on a li...
> phpunit/php-text-template             1.2.1                                     Simple template engine.
> phpunit/php-timer                     2.1.2                                     Utility class for timing
> phpunit/php-token-stream              3.1.1                                     Wrapper around PHP's tokenizer extension.
> phpunit/phpunit                       7.5.20                                    The PHP Unit Testing framework.
> psr/container                         1.0.0                                     Common Container Interface (PHP FIG PSR-11)
> psr/http-message                      1.0.1                                     Common interface for HTTP messages
> psr/log                               1.1.2                                     Common interface for logging libraries
> psr/simple-cache                      1.0.1                                     Common interfaces for simple caching
> psy/psysh                             v0.9.12                                   An interactive shell for modern PHP.
> pusher/pusher-php-server              v3.4.1                                    Library for interacting with the Pusher REST API
> ralouphie/getallheaders               3.0.3                                     A polyfill for getallheaders.
> ramsey/uuid                           3.9.2                                     Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4...
> rap2hpoutre/laravel-log-viewer        v1.3.3                                    A Laravel log reader
> rollbar/rollbar                       v1.8.1                                    Monitors errors and exceptions and reports them to Rollbar
> rollbar/rollbar-laravel               v4.0.3                                    Rollbar error monitoring integration for Laravel projects
> sebastian/code-unit-reverse-lookup    1.0.1                                     Looks up which function or method a line of code belongs to
> sebastian/comparator                  3.0.2                                     Provides the functionality to compare PHP values for equality
> sebastian/diff                        3.0.2                                     Diff implementation
> sebastian/environment                 4.2.3                                     Provides functionality to handle HHVM/PHP environments
> sebastian/exporter                    3.1.2                                     Provides the functionality to export PHP variables for visuali...
> sebastian/global-state                2.0.0                                     Snapshotting of global state
> sebastian/object-enumerator           3.0.3                                     Traverses array structures and object graphs to enumerate all ...
> sebastian/object-reflector            1.1.1                                     Allows reflection of object attributes, including inherited an...
> sebastian/recursion-context           3.0.0                                     Provides functionality to recursively process PHP variables
> sebastian/resource-operations         2.0.1                                     Provides a list of PHP built-in functions that operate on reso...
> sebastian/version                     2.0.1                                     Library that helps with managing the version number of Git-hos...
> spatie/laravel-json-api-paginate      1.6.0                                     A paginator that plays nice with the JSON API spec
> spatie/laravel-query-builder          1.17.5                                    Easily build Eloquent queries from API requests
> swiftmailer/swiftmailer               v6.2.3                                    Swiftmailer, free feature-rich PHP mailer
> symfony/console                       v4.4.2                                    Symfony Console Component
> symfony/css-selector                  v5.0.2                                    Symfony CssSelector Component
> symfony/debug                         v4.4.2                                    Symfony Debug Component
> symfony/error-handler                 v4.4.2                                    Symfony ErrorHandler Component
> symfony/event-dispatcher              v4.4.2                                    Symfony EventDispatcher Component
> symfony/event-dispatcher-contracts    v1.1.7                                    Generic abstractions related to dispatching event
> symfony/finder                        v4.4.2                                    Symfony Finder Component
> symfony/http-foundation               v4.4.2                                    Symfony HttpFoundation Component
> symfony/http-kernel                   v4.4.2                                    Symfony HttpKernel Component
> symfony/mime                          v5.0.2                                    A library to manipulate MIME messages
> symfony/polyfill-ctype                v1.13.1                                   Symfony polyfill for ctype functions
> symfony/polyfill-iconv                v1.13.1                                   Symfony polyfill for the Iconv extension
> symfony/polyfill-intl-idn             v1.13.1                                   Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 funct...
> symfony/polyfill-mbstring             v1.13.1                                   Symfony polyfill for the Mbstring extension
> symfony/polyfill-php72                v1.13.1                                   Symfony polyfill backporting some PHP 7.2+ features to lower P...
> symfony/polyfill-php73                v1.13.1                                   Symfony polyfill backporting some PHP 7.3+ features to lower P...
> symfony/process                       v4.4.2                                    Symfony Process Component
> symfony/routing                       v4.4.2                                    Symfony Routing Component
> symfony/service-contracts             v2.0.1                                    Generic abstractions related to writing services
> symfony/translation                   v4.4.2                                    Symfony Translation Component
> symfony/translation-contracts         v2.0.1                                    Generic abstractions related to translation
> symfony/var-dumper                    v4.4.2                                    Symfony mechanism for exploring and dumping PHP variables
> theseer/tokenizer                     1.1.3                                     A small library for converting tokenized PHP source code into ...
> tightenco/collect                     v5.8.35                                   Collect - Illuminate Collections as a separate package.
> tightenco/ziggy                       v0.6.9                                    Generates a Blade directive exporting all of your named Larave...
> tijsverkoyen/css-to-inline-styles     2.2.2                                     CssToInlineStyles is a class that enables you to convert HTML-...
> vlucas/phpdotenv                      v3.6.0                                    Loads environment variables from `.env` to `getenv()`, `$_ENV`...
> webmozart/assert                      1.6.0                                     Assertions to validate method input/output with nice error mes...

**Comment by jeff1326** [comment]
I created a ticket on https://github.com/sebastianbergmann/php-code-coverage/issues/729 related to this issue since i don't know which one is in problem.

**Comment by kubawerlos** [comment]
I had a very similar issue (coverage working with `xdebug` and `phpdbg`, but not with `pcov`) and it was due to the `pcov.directory` config option.

As in README.md:
> When `pcov.directory` is left unset, PCOV will attempt to find `src`, `lib` or, `app` in the current working directory, in that order; If none are found the current directory will be used, which may waste resources storing coverage information for the test suite.

When I've set it to `.` (e.g. [here](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/blob/v1.17.0/.travis.yml#L48)) all started to work as expected.

**Comment by jeff1326** [comment]
Thanks you @kubawerlos 

I can make it work with `php -d pcov.directory=. ./vendor/bin/phpunit --coverage-html=coverage` but this doesn't work with `phpunit -d pcov.directory=. --coverage-html=coverage`

This is related to : https://github.com/krakjoe/pcov/issues/31

**Comment by sebastianbergmann** [comment]
`phpunit -d` cannot possibly work here and that is expected.

**Comment by ext-pewa** [comment]
> Thanks you @kubawerlos
> 
> I can make it work with `php -d pcov.directory=. ./vendor/bin/phpunit --coverage-html=coverage` but this doesn't work with `phpunit -d pcov.directory=. --coverage-html=coverage`
> 
> This is related to : #31

This did not solve my issue :(

**Comment by rask** [comment]
@ext-pewa you're certain PCOV is loaded (and Xdebug is disabled) when running the tests?

**Comment by ext-pewa** [comment]
> @ext-pewa you're certain PCOV is loaded (and Xdebug is disabled) when running the tests?

yes, however, I just ran it through step by step, and noticed that I was in the wrong directory, so adding an absolute path to pcov.directory seems to have resolved the issue! Thanks :)

Looking at the docs, it seems this is expected, though I think it could be improved so that pcov and phpunit used the same logic to find files. The most confusing part here is the absence of any errors, and the apparent successful generation of a report just with 0% coverage because phpunit and pcov are looking in different places.

In any case, I thank you for your help, and will close the issue.

**Comment by supun-io** [comment]
In my case,  it always said 0% coverage for code in the `/app` folder.

The reason was I had another folder named `/src`, which contained some legacy code. After I renamed it, all were fine!

Hope this helps someone.
