### ISSUE TITLE
Wrong coverage report

### ISSUE THREAD

**Issue by lyrixx** [krakjoe/pcov#48]
Hello, I created a full reproducer [here](https://github.com/lyrixx/test/tree/phpunit).
I made it as small as possible. I hope it will help you.

But basically, The faulty code:

```php
class Sut
{
    public function compute()
    {
        if (true) {
            if (true) {
                $newConfig = [
                    'here' => 'yes',
                ];
            } else {
                $newConfig = [
                    'here' => 'no',
                ];
            }
        } else {
            throw new \RuntimeException('oups');
        }

        return $newConfig;
    }
}
```

When I execute:
```bash
./vendor/bin/phpunit test/ --coverage-html cov
```

It get the following report:

```
^ array:1 [
  "/home/gregoire/dev/github.com/lyrixx/test/src/Sut.php" => array:7 [
    24 => -1
    7 => 1
    8 => 1
    10 => 1
    14 => 1
    18 => -1
    21 => 1
  ]
]
```

![image](https://user-images.githubusercontent.com/408368/78574794-cfe3e500-782a-11ea-80ef-3c4370626410.png)

This is not possible to go through line 10 **and** 14, right ?

And we can go even crazier with the following code:

![image](https://user-images.githubusercontent.com/408368/78575036-1a656180-782b-11ea-82f9-4918f41e93a6.png)

---

PHP:
```
PHP 7.4.4 (cli) (built: Mar 20 2020 13:47:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies
    with blackfire v1.32.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire
```

pcov: 1.0.6

---

Note, I also tested with minimal setup, and I got the same issue:

```
php -n -d extension=dom -d extension=pcov -d extension=tokenizer -d extension=json  ./vendor/bin/phpunit test/ --coverage-html cov
```

**Comment by 5lava** [comment]
(Un)fortunately, It's not PCOV to blame. I observe the same behavior with Xdebug and phpdbg. In fact, I tried a dozen version combinations of PHP, PHPUnit, php-code-coverage, and Xdebug/PCOV/phpdbg. No other extensions were loaded (even opcache.so).

![image](https://user-images.githubusercontent.com/63829/81748503-f9baa800-9477-11ea-978a-68417897a863.png)

**Comment by bwoebi** [comment]
To be precise, the jump at the end of the first if branch to skip the last else is compiled to be present on line 10. IIRC, the idea has been to possibly drop lineno info of these implicit jumps so that they won't appear in coverage reports. But that's a topic for the engine, not this extension in particular.
