### ISSUE TITLE
Question: Is there a functionality of merging the codecoverage reports?

### ISSUE THREAD

**Issue by mlukjanska25f** [krakjoe/pcov#50]
We are running our tests in parallel hence each instance produces it's own codecoverage reports.
So I was wondering if there is a way to merge these reports (both xml and html)?
Is this applicable https://github.com/Nimut/phpunit-merger?

Thanks in advance

**Comment by SamMousa** [comment]
@mlukjanska25f you're in the wrong place.
This library collects coverage but doesn't create any external report.

You should probably close this issue and have a look at this library instead: https://github.com/sebastianbergmann/php-code-coverage
