### ISSUE TITLE
Missing Code Coverage When Phpunit's Process Isolation Is False

### ISSUE THREAD

**Issue by dac514** [krakjoe/pcov#51]
- PHP 7.3.17
- PHPUnit 8.5.5
- pcov 1.0.6

Steps to reproduce:

1. Download attached code: [pcov-bug-report.zip](https://github.com/krakjoe/pcov/files/4754066/pcov-bug-report.zip)
2. `composer install`
3. `./vendor/bin/phpunit --configuration tests/phpunit.xml  --coverage-clover clover.xml`

**Expected:** Accurate code coverage

**Actual:** Missing coverage in switch statements using consts

**Workaround:** If I open tests/phpunit.xml and change `processIsolation="false"` to `processIsolation="true"` the coverage is accurate.

![Screen Shot 2020-06-09 at 1 56 09 PM](https://user-images.githubusercontent.com/812192/84185501-163d0680-aa5d-11ea-8112-44030eddea9e.png)
![Screen Shot 2020-06-09 at 1 56 51 PM](https://user-images.githubusercontent.com/812192/84185514-1d641480-aa5d-11ea-9879-3ddadc1f2d95.png)

---

Zip file contains:

```
.
├── clover-processIsolation-false.xml
├── clover-processIsolation-true.xml
├── composer.json
├── composer.lock
├── src
│   ├── One
│   │   ├── SupportedCountriesISO2.php
│   │   └── SupportedCountriesISO3.php
│   └── Two
│       └── Example.php
└── tests
    ├── Unit
    │   └── ExampleTest.php
    └── phpunit.xml
```

**Comment by dac514** [comment]
Another workaround, in tests/phpunit.xml:

Change: `processUncoveredFilesFromWhitelist="true"` 
To: `processUncoveredFilesFromWhitelist="false"`

**Comment by krakjoe** [comment]
This is an upstream problem: phpuinit is failing to set the interpreter for the new process with the configuration from the parent process.
