### ISSUE TITLE
Windows DLLs for PHP 8.0

### ISSUE THREAD

**Issue by Ayesh** [krakjoe/pcov#57]
Thanks a lot for the work on this great extension. We probably saved several build hours using PCOV. 

I tried to compile pcov on PHP 8.0 branches, and it worked well. Would it be possible to upload Windows DLLs to https://pecl.php.net/package/pcov?

Thank you.

**Comment by cmb69** [comment]
The Windows DLLs are build automatically when a new extension version is released. 1.0.7 has been released recently, but there are issues regarding the Windows builds, starting with #62.

**Comment by remicollet** [comment]
It seems everything is now available

https://pecl.php.net/package/pcov/1.0.8/windows
