### ISSUE TITLE
Issue with empty response with php builtin server

### ISSUE THREAD

**Issue by dominikzogg** [krakjoe/pcov#60]
It seems there is an issue (rare edgecase) using the builtin webserver with pcov and empty responses:

https://github.com/slimphp/Slim-Psr7/issues/189

**Comment by nikic** [comment]
This issue is fixed by https://github.com/krakjoe/pcov/commit/fa3bb62f728bcdd8be2ddcef37f785d79ca63014 as of five minutes ago :)
