### ISSUE TITLE
Release 1.0.8

### ISSUE THREAD

**Issue by remicollet** [krakjoe/pcov#66]
Changes:

- Fix Windows build

**Comment by remicollet** [comment]
FYI @cmb69  

@krakjoe If OK for you, I can take care of it on Monday

**Comment by krakjoe** [comment]
Is fine, and thanks for taking the time /cc @cmb69

**Comment by cmb69** [comment]
Thanks! Looks good to go. :)

**Comment by remicollet** [comment]
Released and announced

**Comment by krakjoe** [comment]
Thanks remi
