### ISSUE TITLE
Pcov using almost 14 GB of memory to generate coverage

### ISSUE THREAD

**Issue by TRowbotham** [krakjoe/pcov#67]
Hi,

While running code coverage on a recent project I discovered that pcov consumed nearly 14 GB of memory and I can't figure out why exactly. I tried code coverage using xdebug and it only used 68 MB of memory to generate coverage for the same code. This was using PHP 7.4.20 on WSL2/Ubuntu 20.04. Please let me know if I can provide any additional information.

Steps to reproduce:
1) Clone https://github.com/TRowbotham/Encoding
2) Run `composer install`
3) Run `php -dextension=<path-to-pcov> vendor/phpunit/phpunit/phpunit --coverage-html build/coverage`

These are the results of running pcov vs xdebug on my PC:
```bash
$ php -dextension=/home/trevor/.phpbrew/php/php-7.4.20/lib/php/extensions/no-debug-non-zts-20190902/pcov.so vendor/phpunit/phpunit/phpunit --coverage-html build/coverage

PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.20 with PCOV 1.0.8
Configuration: /home/trevor/GitHub/Encoding/phpunit.xml

.............................................................   61 / 1375 (  4%)
.............................................................  122 / 1375 (  8%)
.............................................................  183 / 1375 ( 13%)
.............................................................  244 / 1375 ( 17%)
.............................................................  305 / 1375 ( 22%)
.............................................................  366 / 1375 ( 26%)
.............................................................  427 / 1375 ( 31%)
.............................................................  488 / 1375 ( 35%)
.............................................................  549 / 1375 ( 39%)
.............................................................  610 / 1375 ( 44%)
.............................................................  671 / 1375 ( 48%)
.............................................................  732 / 1375 ( 53%)
.............................................................  793 / 1375 ( 57%)
.............................................................  854 / 1375 ( 62%)
.............................................................  915 / 1375 ( 66%)
.............................................................  976 / 1375 ( 70%)
............................................................. 1037 / 1375 ( 75%)
............................................................. 1098 / 1375 ( 79%)
............................................................. 1159 / 1375 ( 84%)
............................................................. 1220 / 1375 ( 88%)
............................................................. 1281 / 1375 ( 93%)
............................................................. 1342 / 1375 ( 97%)
.................................                             1375 / 1375 (100%)

Time: 01:37.026, Memory: 13.84 GB

OK (1375 tests, 427415 assertions)
```

```bash
$ php -dzend_extension=/home/trevor/.phpbrew/php/php-7.4.20/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so -dxdebug.mode=coverage vendor/phpunit/phpunit/phpunit --coverage-html build/coverage

PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.20 with Xdebug 3.0.4
Configuration: /home/trevor/GitHub/Encoding/phpunit.xml

.............................................................   61 / 1375 (  4%)
.............................................................  122 / 1375 (  8%)
.............................................................  183 / 1375 ( 13%)
.............................................................  244 / 1375 ( 17%)
.............................................................  305 / 1375 ( 22%)
.............................................................  366 / 1375 ( 26%)
.............................................................  427 / 1375 ( 31%)
.............................................................  488 / 1375 ( 35%)
.............................................................  549 / 1375 ( 39%)
.............................................................  610 / 1375 ( 44%)
.............................................................  671 / 1375 ( 48%)
.............................................................  732 / 1375 ( 53%)
.............................................................  793 / 1375 ( 57%)
.............................................................  854 / 1375 ( 62%)
.............................................................  915 / 1375 ( 66%)
.............................................................  976 / 1375 ( 70%)
............................................................. 1037 / 1375 ( 75%)
............................................................. 1098 / 1375 ( 79%)
............................................................. 1159 / 1375 ( 84%)
............................................................. 1220 / 1375 ( 88%)
............................................................. 1281 / 1375 ( 93%)
............................................................. 1342 / 1375 ( 97%)
.................................                             1375 / 1375 (100%)

Time: 02:04.912, Memory: 68.00 MB

OK (1375 tests, 427415 assertions)
```

**Comment by TRowbotham** [comment]
I'll note that 99% of the memory is a result of this test https://github.com/TRowbotham/Encoding/blob/3743b014bdc09a98736341f99bc5a284028afecc/tests/Utf8EncodingTest.php#L110-L157

**Comment by krakjoe** [comment]
xdebug does not use zend mm, and so does not report used memory correctly.

please check what the operating system reports.

This is unlikely to be a bug, but a result of the kind of tests you are
running.

**Comment by TRowbotham** [comment]
According to hwinfo64, when running with xdebug, it consumes roughly 1 GB. When running with pcov it consumes roughly 13.7 GB.

**Comment by krakjoe** [comment]
pcov is unaware of the exclude set in xml, see documentation for excluding that directory.

**Comment by TRowbotham** [comment]
I tried deleting the excluded directory and moving it out of the src directory and ran the test mentioned in https://github.com/krakjoe/pcov/issues/67#issuecomment-855337303, as it doesn't use any of the excluded files, and it still uses nearly 14 GB of memory with pcov. That same test uses roughly 30 MB of memory without any code coverage. So, this is not related to not specifying `pcov.exclude`.

I'll see if I can create a reduced test case.

**Comment by krakjoe** [comment]
I'll just explain some words I used:

> This is unlikely to be a bug, but a result of the kind of tests you are running.

pcov maps/mapped the actual path through code as quickly as possible, even though this map will contain duplicate information. I done this so that the data may be used for more than line coverage. None of those other uses have ever actually materialized, and although branch coverage should be on the roadmap somewhere, I've no idea when/if I'll do that.

As a result, code such as this which will heavily repeat instructions will bloat memory usage, quite terribly in this case.

My apologies for being so quick to close; The vast majority of these reports are configuration issues, and as I'm sure you understand, I don't really have the time to test everyone's test suite. I saw a configuration mistake and blamed it on that too quickly.

Please test the latest commit and holla with results.

**Comment by TRowbotham** [comment]
No offense taken, I appreciate you taking the time to investigate it and for the quick fix and the detailed response. It was a valid point as I was in-fact assuming that pcov was aware of the xml exclusion set, so I learned something new.

Agreed about the tests; the offending test iterates over every Unicode code point, which is really expensive as that test alone makes 50+ million function calls.

The results from the 1.0.9-dev build are spectacular, its a little over a minute faster and only consumes about 200 MB of memory according to the OS.

Thanks!

**Comment by krakjoe** [comment]
You're welcome, thanks for fast feedback.
