### ISSUE TITLE
Any way to dynamically change pcov.enabled settings?

### ISSUE THREAD

**Issue by storm1er** [krakjoe/pcov#69]
Hi,

I see `pcov.enabled` is only `Changeable: SYSTEM`,
Is there any way to change it programmatically?

It would be great to be able to use an environment variable to change it on the fly with `dotenv` for example.
Pcov would not start if a `DISABLE_PCOV` env var is detected.

The idea would be to switch on/off with Blackfire for profile/testing purposes =)

**Comment by Agotfrid** [comment]
Have you tried using `php -dpcov.enabled=0` to turn off PCOV while running tests?

**Comment by krakjoe** [comment]
I don't want to off switches, it's too confusing.
