### ISSUE TITLE
No coverage report for inline functions with PHP 8.1

### ISSUE THREAD

**Issue by Khartir** [krakjoe/pcov#70]
I just tested the latest PHP 8.1 beta and noticed that pcov does not report coverage of the body of an inline function.
Code like this:
```php
$callable = function () {
    echo 'foo';
};
$callable();
```
reports no coverage of line 2 at all.

**Comment by andrewbroberg** [comment]
Experiencing the same here on release PHP 8.1.0

**Comment by krakjoe** [comment]
Fixed in HEAD.
