### ISSUE TITLE
What is pcov release schedule? Is it possible to publish a new release soon?

### ISSUE THREAD

**Issue by pgrenaud** [krakjoe/pcov#77]
Greetings,

We observed a bug lately that was recently fixed in develop and we were wondering when is the next release planned? We were unable to find any information about pcov release schedule, hence why this issue. Would you be able to publish a new release soon?

For context about the "bug". We are currently having segmentation faults or abort traps when running brianium/paratest (parallel phpunit) with coverage using pcov. The issue does not come up when using xdebug or not running in parallel or not generating coverage. We built and tested pcov develop branch locally and the issue was no longer occurring. We suspect that PR #75 is what fixed the issue.

Regards,

**Comment by remicollet** [comment]
Version **1.0.10** released

**Comment by pgrenaud** [comment]
Thanks a lot for the quick action!
