### ISSUE TITLE
Alpine binaries?

### ISSUE THREAD

**Issue by marzig76** [krakjoe/pcov#99]
Is there a repo where I can just download pcov binaries outside of apt/rpm?  Specifically for an Alpine linux docker container

**Comment by andypost** [comment]
Alpine using own package manager `apk`, I just added PHP 8.2 compatible version https://pkgs.alpinelinux.org/packages?name=php*pcov&branch=edge&repo=&arch=&maintainer=

**Comment by cmb69** [comment]
So it looks like this ticket can be closed.

**Comment by andypost** [comment]
I hope yes, 8.4 compatible version already present in Alpine testing repo

**Comment by cmb69** [comment]
Unfortunately, I cannot close this ticket, so maybe @marzig76 will do this.
